### ISSUE TITLE
Leaflet.Draw plugin error

### ISSUE THREAD

**Issue by romanrehacek** [Igor-Vladyka/leaflet.browser.print#22]
Hi,

I use your print plugin and everything works fine until I added leaflet.draw plugin.
When I draw something, I cant print map.
There was an error in console
`TypeError: this._renderer._bounds is undefined`

[Here](https://codepen.io/noxonx/pen/bLgqqG) is your example code with Leaflet.Draw plugin.

Can you help me solve this issue please?

**Comment by Igor-Vladyka** [comment]
Hi,

The problem is not with a Draw plugin itself, but with leaflet internal map update structure. I'm still fighting with it and have no idea how to fix it right now in general.

In your case, the best way will be is to add the same FeatureGroup to the nap each time a new object is added to the group. This way it will work as expected. https://codepen.io/anon/pen/EQXBor - modified your example.

Meanwhile, I will try to find a solution to this problem in general.

**Comment by romanrehacek** [comment]
Hi @Igor-Vladyka ,

thank you, it works fine.
I have an another question. It is possible to print opened popup?
It shows, when you draw a marker and click on it.

Thank you.

**Comment by Igor-Vladyka** [comment]
Hi there, 
Please try option closePopupsOnPrint.

Like: L.control.browserPrint({closePopupsOnPrint: false}).add to(map);

You can find more about this on the Readme page.

Regards
Igor

**Comment by romanrehacek** [comment]
Hi,

thank you. Everything works fine.
