### ISSUE TITLE
Print with scale

### ISSUE THREAD

**Issue by mtugnoli** [Igor-Vladyka/leaflet.browser.print#30]
Hi, good work !

my questions :

1) Is it possible to print map in scale ?
2) Is it possible start print scale with external button ? (no inside map like your sample)

**Comment by Igor-Vladyka** [comment]
Hello,

1) What do you mean, in scale? - Do you want to use some plugin to show scale or ... ?
2) Yes, you can print a map from JS. Will add a needed section into documentation shortly. Or please explain your use case in more details.

Regards
Igor

**Comment by mtugnoli** [comment]
Hi Igor,
1. Scale mean ex. 1:25000, 1cm on print is 250mt on ground
2. I would use it in my site (http://mygis.caivola.it/), as you can see I have a toolbar with main commands,
With this html  buttons, (by js), I call leaflet commands

Thank You

Marco

**Comment by Igor-Vladyka** [comment]
I see,

You can call print function of plugin itself. it will allow you to print page
`plugin.print(pageOrientation, bounds);`
The only problem, you still need this plugin on the map (but you can hide it via css, like `.leaflet-control-browser-print{ display: none; }`);

Where - pageOrientation is 'Landscape' or 'Portrait'
And about bounds - you need to calculate bounds on your own for now, to print with a scale. Just calculate needed zoom lvl for your scale (please check this article: https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Resolution_and_Scale) and add 1 zoom lvl for printing, due to: [Issue #31 ](https://github.com/Igor-Vladyka/leaflet.browser.print/issues/31)

So if you need zoom lvl 14, please zoom map on your own to lvl 15 and call the print function with a valid bound calculated for zoom lvl 14.

Or if it's too complicated please wait...., few weeks while I will have time and manage this. :)

Regards,
Igor

**Comment by jrufas** [comment]
Hello,

I've the same need as Marco. As you explain, it isn't very difficult calculate zoom but for bounds calculation, I need the final print size with margin calculation included. I've readed some like this:

        size.Width = Math.floor(calculateMargin(size.Width)) + 'mm';
	    size.Height = Math.floor(calculateMargin(size.Height)) + 'mm';


For me, the logical sequence may be like that:
I supose that I've a mode, scale and paper size fixed (ie. Landscape, 1:5000, A4)

First, I must get the effective paper size (maybe from **_getSize_** function) in mm., then multiply by 5 (5000/1000: mm. to m.).
At this moment I have my rectangle's size in world units (m.).
I can translate to the view's center, calculate bounds in LatLon, then the optimal zoom (for best quality printing) and call the print function.

But ..., I've the feeling that it will not work as I expect.
Maybe it would better getting **_PrePrint_** Event.

Thanks,
Javier

**Comment by Igor-Vladyka** [comment]
Hello, 

You are pretty right about expected workflow, and steps that need to be done :)

But I hope that you understand what Mercado projection will do with scaling? And all these zoom levels :) It's pretty impossible to print a map in exact scale...

Igor
