### ISSUE TITLE
Zoom change on print

### ISSUE THREAD

**Issue by robin-lundberg** [Igor-Vladyka/leaflet.browser.print#31]
Hi, can I disable the zoom change on print? I want it to print the exact same zoom level as is.

**Comment by askart** [comment]
hello, do you use "Auto"? Try to use "Album" or "Portrait".

**Comment by robin-lundberg** [comment]
Hi, I tried all options in different browsers and window sizes. All options zooms out one step.

**Comment by Igor-Vladyka** [comment]
Hello,

This feature is requested for a while now. I will add it to the scope of the next release.

Zoom changes due to a fact that each paper page has ~1.4 proportions width/ height. But in the browser map usually with different proportions, so plugin tries to catch everything that is currently visible on the map, and needs to zoom out to do it...

Regards,
Igor

**Comment by Igor-Vladyka** [comment]
Hi Robin,

Now you can specify if you want to invalidate bounds(zoom level and map center) or not. Please check README for more details. 

Please take latest release v0.6.3 and let me know if any.

Regards,
Igor
