### ISSUE TITLE
Registering layer L.StripePattern in Browser print

### ISSUE THREAD

**Issue by neerajlk** [Igor-Vladyka/leaflet.browser.print#77]
I have this issue in registering a pattern layer in browser-print,I tried adding the below code for registration in the library.

`this.registerLayer(L.StripePattern, 'L.StripePattern', function (layer, utils) {
			return L.StripePattern(layer,utils.cloneOptions(layer.options))
		});`

However on print preview I am getting this error **this.callInitHooks is not a function**

 the library for **L.StripePattern**  is this [leaflet.pattern](https://github.com/teastman/Leaflet.pattern).

Any help will be highly appreciated.

**Comment by Igor-Vladyka** [comment]
Hi,

You should use factory function, or new object for layer registration.
[Here](https://en.wikipedia.org/wiki/Factory_%28object-oriented_programming%29) is more details.
So basically instead of 
`return L.StripePattern(layer,utils.cloneOptions(layer.options))`
just use factory function or add new in front of object creation.
`return L.stripePattern(layer,utils.cloneOptions(layer.options))` 
or
`return new L.StripePattern(layer,utils.cloneOptions(layer.options))`
