### ISSUE TITLE
Print preview on same page

### ISSUE THREAD

**Issue by nsenkevich** [Igor-Vladyka/leaflet.browser.print#84]
Hey,
First of all Thanks for the plugin, great job.

I just wondering how hard it will be to display print preview on same page with some controls like Paper size, orientation, scale. See print screens:
<img width="1594" alt="Screenshot 2020-02-09 01 47 11" src="https://user-images.githubusercontent.com/1181279/74094858-07ab0680-4ae0-11ea-84b7-ee072fa03156.png">
<img width="1324" alt="Screenshot 2020-02-09 01 46 53" src="https://user-images.githubusercontent.com/1181279/74094859-0bd72400-4ae0-11ea-9dd0-dab890b1db24.png">

Thanks
Nikolai

**Comment by Igor-Vladyka** [comment]
Hi Nikolai,

From development perspective, it's entirelly new plugin.

Regards,
Igor

**Comment by AlbertoMCS** [comment]
Hi @nsenkevich, did you manage to create/find something similar to what you suggested? I think there is a massive gap when using leaflet and wanting to have a proper printing capabilities as you said, defining edges of the page, scale, paper size etc. Igor's plugin is massively useful, but as he said, in order to get a better one, it would be needed to do it from scratch. Do you know any commercial plugin out there?
